---
apiVersion: v1
kind: Service
metadata:
  name: backend-serivce
  labels:
    app: payvoo_service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: payvoo_service
