---
apiVersion: v1
kind: Service
metadata:
  name: frontend-serivce
  labels:
    app: payvoo_web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: payvoo_web