---
apiVersion: v1
kind: Service
metadata:
  name: merchant-frontend-serivce
  labels:
    app: payvoo_merchant
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: payvoo_merchant