ALTER TABLE `country`
ADD COLUMN (`iso_currency_name` varchar(250) DEFAULT NULL);

UPDATE `country` SET `iso_currency_name`='Bulgarian lev' WHERE `country_id`='1';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='2';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='3';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='4';
UPDATE `country` SET `iso_currency_name`='Indian rupee' WHERE `country_id`='5';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='6';
UPDATE `country` SET `iso_currency_name`='Croatian kuna' WHERE `country_id`='7';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='8';
UPDATE `country` SET `iso_currency_name`='Czech koruna' WHERE `country_id`='9';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='10';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='11';
UPDATE `country` SET `iso_currency_name`='Danish krone' WHERE `country_id`='12';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='13';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='14';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='15';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='16';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='17';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='18';
UPDATE `country` SET `iso_currency_name`='Swedish krona/kronor' WHERE `country_id`='19';
UPDATE `country` SET `iso_currency_name`='British Pound sterling' WHERE `country_id`='20';
UPDATE `country` SET `iso_currency_name`='Hungarian forint' WHERE `country_id`='21';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='22';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='23';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='24';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='25';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='26';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='27';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='28';
UPDATE `country` SET `iso_currency_name`='Polish zloty' WHERE `country_id`='29';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='30';
UPDATE `country` SET `iso_currency_name`='Romanian leu' WHERE `country_id`='31';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='32';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='33';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='34';
UPDATE `country` SET `iso_currency_name`='United States dollar' WHERE `country_id`='35';
UPDATE `country` SET `iso_currency_name`='Euro' WHERE `country_id`='36';