apiVersion: v1
kind: Service
metadata:
  name: payvoo
  namespace: payvoo
spec:
  selector:
    name: payvoo
  ports:
  - name:  Backend
    port:  3000
    targetPort:  3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payvoo
  namespace: payvoo
spec:
  selector:
    matchLabels:
      app: payvoo
  template:
    metadata:
      labels:
        app: payvoo
    spec:
      containers:
      - name: payvoo-backend
        image: registry.gitlab.com/incrivelsoft/payvoo/backend
        env:
          - name: PORT
            value: "3000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      - name: payvoo-web
        image: registry.gitlab.com/incrivelsoft/payvoo/web
        env:
          - name: PORT
            value: "3000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: payvoo-merchant
        image: registry.gitlab.com/incrivelsoft/payvoo/merchant
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
